variable "name" {
  type = string
  default = "imperva-dsf-hub"
  description = "Deployment name"
  validation {
    condition = length(var.name) > 3
    error_message = "Deployment name must be at least 3 characters"
  }
}

variable "subnet_id" {
  type = string
  description = "Subnet id for the DSF hub instance"
  validation {
    condition     = length(var.subnet_id) >= 15 && substr(var.subnet_id, 0, 7) == "subnet-"
    error_message = "Subnet id is invalid. Must be subnet-********."
  }
}

variable "instance_type" {
  type = string
  default = "r6i.2xlarge"
  description = "Ec2 instance type for the DSF hub"
}

variable "disk_size" {
  default = 510
  validation {
    condition     = var.disk_size >= 500
    error_message = "DSF hub instance disk size must be at least 500GB"
  }
}

variable web_console_sg_ingress_cidr {
  type = list
  description = "List of allowed ingress cidr patterns for the DSF hub instance for web console"
}

variable sg_ingress_cidr {
  type = list
  description = "List of allowed ingress cidr patterns for the DSF hub instance for ssh and internal protocols"
}

variable "key_pair" {
  type = string
  description = "key pair for DSF hub instance. This key must be generated by by the hub module and present on the local disk"
}

variable "tarball_bucket_name" {
  type = string
  description = "The s3 bucket name. This is used to create a proper IAM profile for the ec2 instance"
}

variable "hadr_secondary_node" {
  type = bool
  default = false
  description = "Is this node a hadr secondary one"
}

variable "hadr_main_hub_sonarw_secret" {
  type = object({
    name = string
    arn = string
  })
  default = null
  description = "Secret of sonarw taken from the main hub node. This var must be defined for hadr seconday node"
}
