variable "resource_group" {
  type = object({
    name     = string
    location = string
  })
  description = "Resource group details"
}

variable "name" {
  type = string
}

variable "subnet_id" {
  type        = string
  description = "Subnet id for the DSF base instance"
}

variable "instance_type" {
  type        = string
  description = "vm type for the DSF base instance"
}

variable "storage_details" {
  type = object({
    storage_account_type = string
    disk_iops_read_write = number
    disk_size            = number
  })
  description = "Compute instance volume attributes"
}

variable "create_and_attach_public_elastic_ip" {
  type        = bool
  description = "Create public IP for the instance"
}

variable "use_public_ip" {
  type        = bool
  description = "Create public IP for the instance"
}

variable "public_ssh_key" {
  type        = string
  description = "key pair for DSF base instance default user. This key must be generated by the hub or gw module and present on the local disk."
}

# tbd: use this
# variable "web_console_cidr" {
#   type        = list(any)
#   description = "List of allowed ingress cidr patterns for the DSF instance for web console"
#   default     = []
# }

variable "sg_ingress_cidr" {
  type        = list(any)
  description = "List of allowed ingress cidr patterns for the DSF instance for ssh and internal protocols"
}

# tbd: use these
# variable "iam_instance_profile_id" {
#   type        = string
#   default     = null
#   description = "DSF base ec2 IAM instance profile id"
# }

# variable "ami_name_tag" {
#   type = string
# }

# variable "ami_user" {
#   type = string
# }

variable "resource_type" {
  type = string
  validation {
    condition     = contains(["hub", "gw"], var.resource_type)
    error_message = "Allowed values for dsf type \"hub\" or \"gw\"."
  }
  nullable = false
}

variable "web_console_admin_password" {
  type        = string
  sensitive   = true
  description = "Admin password"
  validation {
    condition     = length(var.web_console_admin_password) > 8
    error_message = "Admin password must be at least 8 characters"
  }
  nullable = false
}

variable "ssh_key_path" {
  type        = string
  description = "SSH key path"
  nullable    = false
}

variable "additional_install_parameters" {
  default = ""
}

variable "binaries_location" {
  type = object({
    az_storage_account = string
    az_container       = string
    az_blob            = string
  })
  description = "Azure DSF installation location"
  nullable    = false
}

variable "hadr_secondary_node" {
  type        = bool
  default     = false
  description = "Is this node a HADR secondary one"
}

variable "sonarw_public_key" {
  type        = string
  description = "Public key of the sonarw user taken from the primary node output. This variable must only be defined for the secondary node."
  default     = null
}

variable "sonarw_private_key" {
  type        = string
  description = "Private key of the sonarw user taken from the primary node output. This variable must only be defined for the secondary node."
  default     = null
}

variable "proxy_info" {
  type = object({
    proxy_address      = string
    proxy_ssh_key_path = string
    proxy_ssh_user     = string
  })
  description = "Proxy address, private key file path and user used for ssh to a private DSF node. Keep empty if a proxy is not used."
  default = {
    proxy_address      = null
    proxy_ssh_key_path = null
    proxy_ssh_user     = null
  }
}

variable "hub_sonarw_public_key" {
  type        = string
  description = "Public key of the sonarw user taken from the primary Hub output. This variable must only be defined for the Gateway. Used, for example, in federation."
  default     = null
}

variable "skip_instance_health_verification" {
  description = "This variable allows the user to skip the verification step that checks the health of the EC2 instance after it is launched. Set this variable to true to skip the verification, or false to perform the verification. By default, the verification is performed. Skipping is not recommended"
}
