variable "name" {
  type = string
}

variable "subnet_id" {
  type = string
  description = "Subnet id for the ec2 instance"
}

variable "ec2_instance_type" {
  type = string
  description = "Ec2 instance type for the DSF base instance"
}

variable "aws_ami_name" {
  type = string
  description = "Name of the base AMI to use when deploying the dsf instnace."
}

variable "ebs_disk_size" {
  validation {
    condition     = var.ebs_disk_size >= 100
    error_message = "DSF base instance disk size must be at least 100GB."
  }
}

variable "ec2_user_data" {
  type = string
}

variable "key_pair" {
  type = string
  description = "key pair for DSF base instance. This key must be generated by by the hub module and present on the local disk."
}

variable "key_pair_pem_local_path" {
  type = string
  description = "Path to local key pair used to access dsf instances via ssh to run remote commands"
}

variable "security_group_ingress_cidrs" {
  type = list
  description = "List of allowed ingress cidr patterns for the DSF base instance"
}

variable "dsf_iam_profile_name" {
  type = string
  default = null
  description = "DSF base ec2 IAM instance profile"
}

variable "dsf_base_amis_id" {
  type = map(any)
  default = {
    us-east-1 = "ami-064196ba51ee65773"
    eu-west-2 = "ami-03a6c38b3c0aa74f9"
  }
}
