#!/bin/bash -x
set -e

client_id=terraform-automation
reason="Token autogenerated by terraform"

# Generate access token to hub
cat << EOF > generate_token.sh
sudo curl -w '\n' \
    --cacert \$JSONAR_LOCALDIR/ssl/ca/ca.cert.pem \
    --cert \$JSONAR_LOCALDIR/ssl/client/admin/cert.pem \
    --key \$JSONAR_LOCALDIR/ssl/client/admin/key.pem \
    -X POST 'https://localhost:27920/tokens' \
    -H 'Content-type: application/json' \
    -d '{"client_id":"'$client_id'","user":"admin","reason":"'"$reason"'","grants":["usc:access"]}' | cut -d\" -f4
EOF

scp -o StrictHostKeyChecking="no" -i ${ssh_key_path} generate_token.sh ec2-user@${dsf_hub_address}:generate_token.sh
ssh -o StrictHostKeyChecking="no" -i ${ssh_key_path} ec2-user@${dsf_hub_address} -C "chmod +x ./generate_token.sh && ./generate_token.sh" > hub_token
hub_token=$(cat hub_token)
echo token: $hub_token

# Run oboarder jar
java -jar ${module_path}/artifacts/sonar_onboarder-1.4-SNAPSHOT-all.jar ${db_arn} ${dsf_hub_address} $hub_token ${assignee_gw} ${db_user} ${db_password}
