#!/bin/bash

client_id="terraform-automation"
reason="Token autogenerated by terraform"

# Generate access token to hub
sudo curl -w '\n' \
    --cacert $JSONAR_LOCALDIR/ssl/ca/ca.cert.pem \
    --cert $JSONAR_LOCALDIR/ssl/client/admin/cert.pem \
    --key $JSONAR_LOCALDIR/ssl/client/admin/key.pem \
    -X POST 'https://localhost:27920/tokens' \
    -H 'Content-type: application/json' \
    -d '{"client_id":"'$client_id'","user":"admin","reason":"'"$reason"'","grants":["usc:access"]}' | cut -d\" -f4
