variable "name" {
  type = string
  default = "imperva-dsf-agentless-gw"
  description = "Deployment name"
  validation {
    condition = length(var.name) > 3
    error_message = "Deployment name must be at least 3 characters"
  }
}

variable "subnet_id" {
  type = string
  description = "Subnet id for the DSF agentless gw ec2 instance"
  validation {
    condition     = length(var.subnet_id) >= 15 && substr(var.subnet_id, 0, 7) == "subnet-"
    error_message = "Subnet id is invalid. Must be subnet-********"
  }
}

variable "public_ip" {
  type = bool
  default = false
  description = "Create public IP for the instance"
}

variable "instance_type" {
  type = string
  default = "c5.9xlarge"
  description = "Ec2 instance type for the DSF agentless gw"
}

variable "disk_size" {
  default = 150
  validation {
    condition     = var.disk_size >= 150
    error_message = "DSF agentless gw disk size must be at least 150GB"
  }
}

variable sg_ingress_cidr {
  type = list
  description = "List of allowed ingress cidr patterns for the DSF agentless gw instance for ssh and internal protocols"
}

#variable sg_ingress_hub {
#  type = string
#  description = "Allowed ingress sg id for the DSF hub instance"
#}

variable "key_pair" {
  type = string
  description = "key pair for DSF agentless gw ec2 instance. This key must be generated by by the hub module and present on the local disk"
}

variable "tarball_bucket_name" {
  type = string
  description = "The s3 bucket name. This is used to create a proper IAM profile for the ec2 instance"
}
