name: 'Nightly Manager'

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 20 * * *'

permissions:
  contents: read

jobs:
  master_dsf_poc:
    uses: imperva/dsfkit/.github/workflows/dsf_poc_cli.yml@fix-matrix-generation
    with:
      use_modules_from_terraform_registry: true
      explicit_ref: fix-matrix-generation
      deployment_type: "all"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DAM_LICENSE: ${{ secrets.DAM_LICENSE }}
      ALLOWED_SSH_CIDRS: ${{secrets.ALLOWED_SSH_CIDRS }}
      DEPLOYMENT_TAGS: ${{ secrets.DEPLOYMENT_TAGS }}

  dev_dsf_poc:
    uses: imperva/dsfkit/.github/workflows/dsf_poc_cli.yml@fix-matrix-generation
    with:
      use_modules_from_terraform_registry: false
      explicit_ref: fix-matrix-generation
      deployment_type: "all"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DAM_LICENSE: ${{ secrets.DAM_LICENSE }}
      ALLOWED_SSH_CIDRS: ${{secrets.ALLOWED_SSH_CIDRS }}
      DEPLOYMENT_TAGS: ${{ secrets.DEPLOYMENT_TAGS }}

  master_dsf_poc_azure:
    uses: imperva/dsfkit/.github/workflows/dsf_poc_cli_azure.yml@fix-matrix-generation
    with:
      use_modules_from_terraform_registry: true
      explicit_ref: fix-matrix-generation
      deployment_type: "all"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DAM_LICENSE: ${{ secrets.DAM_LICENSE }}

  dev_dsf_poc_azure:
    uses: imperva/dsfkit/.github/workflows/dsf_poc_cli_azure.yml@fix-matrix-generation
    with:
      use_modules_from_terraform_registry: false
      explicit_ref: fix-matrix-generation
      deployment_type: "all"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DAM_LICENSE: ${{ secrets.DAM_LICENSE }}

