name: Sonar Only Workflows - Dummy Workflow

on:
  workflow_dispatch:  # This allows the workflow to be manually triggered from the GitHub UI

jobs:
  dummy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Just a dummy step
        run: echo "This is a dummy workflow doing nothing."
